### ISSUE TITLE
Link

### ISSUE THREAD

**Issue by Philipp1804** [rstropek-teaching/turmrechnen-quiz-4bhif-Philipp1804#1]
https://stackblitz.com/edit/angular-ibtnth

https://angular-ibtnth.stackblitz.io

**Comment by rstropek** [comment]
Hi @Philipp1804 

You are nearly there. The button is not disabled if the form's content is invalid. The table's HTML is also not completely correct. Fix these two issues and your extra point will be secured.

Greetings,
Rainer Stropek.
